import:
  - logstash-plugins/.ci:travis/defaults.yml@1.x
  - logstash-plugins/.ci:travis/exec.yml@1.x

env:
  jobs:
    - ELASTIC_STACK_VERSION=8.current DOCKER_ENV=dockerjdk21.env
    - SNAPSHOT=true ELASTIC_STACK_VERSION=8.current DOCKER_ENV=dockerjdk21.env